name: Validate code format with clang-format

on: 
  - push
  - pull_request

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: "*"  # Here, this is the directory or files to check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.9.0
        with: 
          clang-format-version: "15"
          check-path: ${{ matrix.path['check'] }}  # Files to check
          exclude-regex: 'lib/.*'  # Excluding everything inside the lib folder
          fallback-style: "Google"
